export const ICONS = {
	ARROW_LEFT: 'arrow-left',
	ARROW_RIGHT: 'arrow-right',
	ARROW_UP: 'arrow-up',
	ARROW_DOWN: 'arrow-down',
	BASKET: ' basket',
	CLOSE: 'close',
	CHECKBOX_EMPTY: 'checkbox-empty',
	CHECKBOX_FILLED: 'checkbox-filled',
	CONFIRM: 'confirm',
	DELETE: 'delete',
	DROP_DOWN_MENU: 'drop-down-menu',
	EDIT: 'edit',
	GARBAGE: 'garbage',
	GOOGLE: 'google',
	HIDE_PASSWORD: 'hide-password',
	INFO: 'info',
	LOG_OUT: 'log-out',
	LORRY: 'lorry',
	MINUS: 'minus',
	PLUS: 'plus',
	PLAY: 'play',
	PAUSE: 'pause',
	PLAY_IN_CIRCLE: 'play-circle',
	SHOW_PASSWORD: 'show-password',
	USER: 'user',
	TEXT: 'text-icon',
	CLOCK: 'clock',
	CALENDAR: 'calendar',
	DESCRIPTION: 'description',
	COLOR_PICKER: 'color-picker',
	SIGN_OUT: 'sign-out',
} as const;
